### 12. Connect to sql and write a query to get list of Provider names whose Providername is starting with letter T.

In [2]:
import pandas as pd
import sqlite3

In [4]:
workbook_url = 'HospitalDatabase.xlsx'
Providers_df = pd.read_excel(workbook_url,sheet_name='Providers')
Providers_df

    ProviderID     ProviderName ProviderSpecialty     ProviderDateOnStaff
0            1        Sally Sue        Pediatrics 1993-01-01 00:00:00.000
1            2       Mike Myers        Pediatrics 1993-05-02 00:00:17.695
2            3   Jordan Michael        Pediatrics 1993-06-24 21:31:46.687
3            4        Ted Texas        Pediatrics 1993-12-23 21:33:52.299
4            5         Ala Bama        Pediatrics 1995-01-10 02:53:47.838
5            6       Harry Kane        Pediatrics 1995-07-21 03:49:03.310
6            7        Barry Bar        Pediatrics 1995-11-21 19:30:38.759
7            8        Ted Green        Pediatrics 1996-05-30 06:14:52.539
8            9        Ted Black        Pediatrics 1997-02-20 08:01:10.211
9           10         Fred Man           Surgery 1998-03-17 01:47:18.794
10          11     Kim Kimberly           Surgery 1998-05-10 14:47:29.468
11          12         Sarah Ab           Surgery 1998-08-18 05:22:40.762
12          13  Abigail Marriot           Surgery 1998-11-08 12:25:45.705
13          14          Dave Yu           Surgery 1999-06-26 16:18:57.436
14          15  Christian Saint           Surgery 2000-08-27 00:12:40.326
15          16     Perry Pardon           Surgery 2001-02-13 11:49:17.862
16          17     Kent Kendall        Cardiology 2001-12-22 11:18:32.919
17          18       Ryan Kevin        Cardiology 2003-01-14 21:16:34.778
18          19     Tyler Conner        Cardiology 2003-07-09 02:41:40.410
19          20    Bailey Barret        Cardiology 2003-08-20 16:05:50.179
20          21      Megan Bonco        Cardiology 2004-02-17 21:22:30.546
21          22    Joesph Walter        Cardiology 2005-02-04 11:40:44.121
22          23      Walter King        Cardiology 2006-03-12 22:11:58.070
23          24        Luke Long        Cardiology 2006-04-28 00:16:36.762
24          25      Justin Time       PrimaryCare 2006-06-21 04:46:36.838
25          26      Mike Joseph       PrimaryCare 2006-12-29 16:26:41.085
26          27   Bridget Brenda       PrimaryCare 2007-06-30 05:53:46.143
27          28      Brenda Bing       PrimaryCare 2007-11-18 22:33:55.792
28          29    Chandler Bing       PrimaryCare 2007-12-07 23:50:10.442
29          30      Joesph Ross       PrimaryCare 2008-11-08 18:06:32.983
30          31     Dwight Scott       PrimaryCare 2009-04-18 19:15:44.587
31          32  Michael Halpert       PrimaryCare 2009-09-02 00:14:41.441
32          33      Pamela Ding       PrimaryCare 2009-11-12 03:59:49.655
33          34       Tony Creed       PrimaryCare 2010-04-28 14:11:26.802
34          35  Phyllis Stanley       PrimaryCare 2011-05-05 16:06:03.222
35          36        Holly Hue       PrimaryCare 2012-06-24 06:55:22.021
36          37        Trent Tye       PrimaryCare 2013-01-12 15:32:21.137
37          38    Kimberly Cone       PrimaryCare 2013-05-23 05:17:19.360
38          39       Harry West       PrimaryCare 2013-07-14 00:22:03.151
39          40     Rosie Renter       PrimaryCare 2013-09-11 12:07:55.584

In [6]:
# Write any Database Name you like, this will create a .db file in the same folder 
# where you're storing this Jupyter Notebook file
conn = sqlite3.connect('Neha_SQL.db')
Providers_df.to_sql('Providers', conn, if_exists='replace', index=False)
# Create a cursor object
cur = conn.cursor()
select_all = "SELECT * FROM Providers WHERE ProviderName LIKE 'T%'"

rows = cur.execute(select_all).fetchall()
 
# Output to the console screen
for r in rows:
    print(r)

# Close connection to SQLite database
conn.close()

(4, 'Ted Texas', 'Pediatrics', '1993-12-23 21:33:52.299000')
(8, 'Ted Green', 'Pediatrics', '1996-05-30 06:14:52.539000')
(9, 'Ted Black', 'Pediatrics', '1997-02-20 08:01:10.211000')
(19, 'Tyler Conner', 'Cardiology', '2003-07-09 02:41:40.410000')
(34, 'Tony Creed', 'PrimaryCare', '2010-04-28 14:11:26.802000')
(37, 'Trent Tye', 'PrimaryCare', '2013-01-12 15:32:21.137000')